server:
    port: ${PORT:9000}
spring:
  application:
      name: task-manager
      date: '@build.date@'
      version: '@build.version@'
  profiles.active: local
  messages.encoding: UTF-8
liquibase:
    enabled: true
    change-log: classpath:db/master.xml
app:
  fixedDelay:
    validateTask: 1000
    hashSolveTask: 1000
    removeOld: 1000
  removeMoreDays: 7

logging:
    config: classpath:logback.xml

